CREATE DATABASE IF NOT EXISTS `rycrm-master` DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS `rycrm-tenant-1` DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS `rycrm-tenant-2` DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;