ALTER TABLE `master_tenant`
    MODIFY COLUMN `TENANT` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '租户ID' AFTER `ID`,
    MODIFY COLUMN `URL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '数据库连接URL' AFTER `TENANT`,
    ADD COLUMN `database_name` varchar(64) NULL COMMENT '数据库名' AFTER `URL`,
    ADD COLUMN `create_time` datetime(0) NULL COMMENT '创建时间' AFTER `PASSWORD`;
    MODIFY COLUMN `USERNAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户名' AFTER `URL`,
    MODIFY COLUMN `PASSWORD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '密码' AFTER `USERNAME`;